### ISSUE TITLE
Use line breaks to increase code readability

### ISSUE THREAD

**Issue by sen1** [cwsvensson/pwp-capstones#1]
You have:
```
text_prep = text.replace("?", ".").replace("!", ".").replace(",", "").replace("..", ".").replace("..", ".")
```

It generally very odd to read. I would do one step at a time:
```
no_questions = text.replace('?', '.')
no_exclaim = no_questions.replace('!', '.')
..
```

Also, you have `replace("..", ".")`.

**Comment by cwsvensson** [comment]
Yes, I agree, but I also wanted to demonstrate knowledge of chaining functions.  As for the comment that I have a .replace("..", ".") please see the next issue where it is combined with that issue's details.
